name: Test and Build 🎮

on:
  push:
    paths: ["Assets/**", ".github/workflows/**"]
    branches: ['*', '!main']
    

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
        
  test:
    needs: lint
    uses: ./.github/workflows/test.yml
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

  build:
    needs: test
    uses: ./.github/workflows/build.yml
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
